
    const START_WHITE_END_BLACK_INDEX = 23
    const START_BLACK_END_WHITE_INDEX = 0
    const HOME_AREA_LENGTH = 6
    const MAX_COINS_OUT = 15
export {START_BLACK_END_WHITE_INDEX, START_WHITE_END_BLACK_INDEX, HOME_AREA_LENGTH, MAX_COINS_OUT} 